on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Re-deploy depdendents
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.DEPLOY50_PAT }}
          script: |
            const dependents = [
                ['ai', '2020/x'],
                ['ai', '2022/summer'],
                ['ai', '2022/fall'],
                ['ap', '2022'],
                ['beyond', '2019/x'],
                ['business', '2017/x'],
                ['business', '2022/summer'],
                ['cs50.tf', 'main'],
                ['games', '2018/x'],
                ['harvard', '2022/fall'],
                ['harvard', '2022/summer'],
                ['harvard', '2022/x'],
                ['hbap.io', 'main'],
                ['hbs', '2022/fall'],
                ['law', '2019/x'],
                ['mobile', '2018/x'],
                ['python', '2022/x'],
                ['scratch', '2021/x'],
                ['technology', '2017/x'],
                ['technology', '2022/fall'],
                ['web', '2020/x'],
                ['web', '2022/summer'],
                ['web', '2022/fall'],
                ['yale', '2022/summer'],
                ['yale', '2022/fall']
            ];
            for (let dependent of dependents) {
                await github.rest.actions.createWorkflowDispatch({
                  owner: 'cs50',
                  repo: dependent[0],
                  workflow_id: 'main.yml',
                  ref: dependent[1]
                });
            }
